pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "tkwk5445/todo-frontend:latest" // Docker 이미지 이름
        FRONTEND_REPO = "https://github.com/tkwk5445/devops_todo_app.git" // 프론트엔드 레포지토리 URL
        FRONTEND_PATH = "frontend" // 프론트엔드 코드 경로
    }
    stages {
        stage('Clone Repository') {
            steps {
                echo "Cloning repository: ${FRONTEND_REPO}"
                git branch: 'main', url: "${FRONTEND_REPO}"
            }
        }
        stage('Generate .env File') {
            steps {
                echo "Generating .env file in frontend directory"
                sh '''
                echo "REACT_APP_API_URL=${REACT_APP_API_URL}" >> ${WORKSPACE}/frontend/.env
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image: ${DOCKER_IMAGE}"
                dir(FRONTEND_PATH) {
                    sh 'docker build -t $DOCKER_IMAGE .' // Docker 이미지 빌드
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                echo "Pushing Docker image: ${DOCKER_IMAGE}"
                withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
                    docker push $DOCKER_IMAGE
                    '''
                }
            }
        }
    }
}