pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "tkwk5445/todo-backend:latest" // Docker 이미지 이름
        BACKEND_REPO = "https://github.com/tkwk5445/devops_todo_app.git" // 프론트엔드 레포지토리 URL
        BACKEND_PATH = "backend" // 프론트엔드 코드 경로
    }
    stages {
        stage('Clone Repository') {
            steps {
                echo "Cloning repository: ${BACKEND_REPO}"
                git branch: 'main', url: "${BACKEND_REPO}" // Git 레포지토리 클론
            }
        }
        stage('Build Docker Image') {
            steps {
                echo "Building Docker image: ${DOCKER_IMAGE}"
                dir(BACKEND_PATH) {
                    sh 'docker build -t $DOCKER_IMAGE .' // Docker 이미지 빌드
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                echo "Pushing Docker image: ${DOCKER_IMAGE}"
                // Docker Hub 자격 증명 사용
                withCredentials([usernamePassword(credentialsId: 'docker-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    docker login -u $DOCKER_USER -p $DOCKER_PASS
                    docker push $DOCKER_IMAGE
                    '''
                }
            }
        }
    }
}
